### ISSUE TITLE
Decide whether or not we can accessibly implement form labels as designed

### ISSUE THREAD

**Issue by mattstauffer** [tighten/built-with-laravel#12]
<img width="638" alt="image" src="https://github.com/user-attachments/assets/f51b791f-b77b-4808-9d16-82f2773652b3">

Normally we could do one of the things where the label shows inside the input until you click it, and then it zooms up above. But the design of this is so tight that there's no space for it.

So this may be not possible. :shrug:

**Comment by tonysm** [comment]
Taking a look at this one
