### ISSUE TITLE
Update technologies on the form to be sexy select thingy

### ISSUE THREAD

**Issue by mattstauffer** [tighten/built-with-laravel#8]
**Desktop:**
<img width="625" alt="image" src="https://github.com/user-attachments/assets/1568abd7-a23c-42d1-a659-ddefe4f1da0f">

**Mobile:**
<img width="293" alt="image" src="https://github.com/user-attachments/assets/88cf33bc-5a8d-45c3-9454-2150cccc1cf8">

**Comment by tonysm** [comment]
Tackling this one too
